<h3>This receipt was generated by QrcodePay</h3>
<p style="color:black;">
    Thank you for donating to <strong>{{$vendorName}}</strong> <br>
    Donation amount: ${{$amount}}NZD
    <br>
    <br>
    <strong>{{$vendorName}}</strong> registration number: <strong>{{$registrationNum}}</strong>   <br>

    Transaction ID <strong>{{$transactionNum}}</strong>   <br>

    All payments processed by Stripe.
</p>
